---
apiVersion: v1
kind: Service
metadata:
  name: stateful-site
spec:
  type: NodePort
  selector:
    app: stateful-site
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 80 
