---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-site
spec:
  selector:
    matchLabels:
      app: static-site
  replicas: 1
  template:
    metadata:
      labels:
        app: static-site
    spec:
      containers:
      - name: static-site
        image: danieldsj/static-site
        ports:
        - containerPort: 80
